### ISSUE TITLE
Conda-forge? 

### ISSUE THREAD

**Issue by jan-janssen** [abinit/abiconda#1]
I had some issues to get the abinit package to work with conda-forge - mainly an issue with the netcdf pinning. So I started to create a conda-forge recipe instead. https://github.com/conda-forge/abinit-feedstock

I wanted to ask: Are you interested in joining me in maintaining the conda-forge recipe?

**Comment by gmatteo** [comment]
> I had some issues to get the abinit package to work with conda-forge - mainly an issue with the netcdf pinning. So I started to create a conda-forge recipe instead. https://github.com/conda-forge/abinit-feedstock

Great idea! 

Moving the recipes to conda-forge was in my TODO list but I didn't have time to work on it. 
I encountered problems with the netcdf pinning as well.  In particular now it's difficult to install both Abinit and AbiPy in the same conda env. Hopefully migrating both Abinit and Abipy to conda-forge will fix these problems.

I've created the abiconda channel to provide conda packages for  AbiPy as, as that time, pymatgen was not in conda-forge and one had to use the matsci channel.
Now there are conda-forge packages for  pymatgen and spglib so AbiPy can be moved to conda-forge as well (AbiPy is a pure python package so the installation is relatively easy)

I had a look at your recipe and I see that you are still using Abinit8.
In principle, it would be great if we can support Abinit version >= 9 only 
but there are some technical points it's  worth considering:

1. We have a new build system in v9 and some configuration options have been renamed.
   I can help with the changes required to migrate to v9.

2. In v9, libxc, netcdf4, and hdf5 have become hard-dependencies. Fortunately all these packages are in conda-forge so this is not a big deal. 

Last but not least, I use the abinit binaries provided by abiconda for running the AbiPy integration tests with Travis. We plan to drop support for Abinit8 in AbiPy v1.0 and this is the reason why I would prefer to have conda recipes for Abinit >= 9 only.

**Comment by jan-janssen** [comment]
I have to admit I was involved in the matsci migration to conda-forge as well https://github.com/materialsvirtuallab/materials.sh/issues/4 

I added you to both abinit and abipy. 
https://github.com/conda-forge/abinit-feedstock/pull/17 And https://github.com/conda-forge/abipy-feedstock/pull/1

I had trouble updating to v9 before but that might be related to libxc 5.0.0 - I am going to look at it again.

**Comment by gmatteo** [comment]
> I had trouble updating to v9 before but that might be related to libxc 5.0.0 - I am going to look at it again.

Libxc5 is not yet supported. There has been some work in our internal version to add support for libxc5.
Note, however,  that libxc 5.0.0 is affected by serious bugs and the developers are planning a [hotfix release](https://gitlab.com/libxc/libxc/-/issues/186).
Seel also https://gitlab.com/libxc/libxc/-/issues/185
